CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login VARCHAR(100) NOT NULL,
  senha VARCHAR(45) NOT NULL,
  nome_completo VARCHAR(45) NOT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  status INTEGER NOT NULL,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  reset_token TEXT,
  reset_token_expiry TIMESTAMP
);

CREATE TABLE produtos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    descricao TEXT NOT NULL,
    imagem TEXT NOT NULL, -- Caminho da imagem
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

