CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login VARCHAR(100) NOT NULL,
  senha VARCHAR(45) NOT NULL,
  nome_completo VARCHAR(45) NOT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  status INTEGER NOT NULL,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);